# .github/workflows/playwright.yml

# Name for the workflow
name: Playwright Tests & Allure Report

# Triggers the workflow on push or pull request events for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# A workflow run is made up of one or more jobs
jobs:
  # This job runs the tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm test # This will generate allure-results
        env:
          TEST_USERNAME: ${{ secrets.TEST_USERNAME }}
          TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
          TEST_EMAIL: ${{ secrets.TEST_EMAIL }}

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results
          retention-days: 1 # We only need the results for the next job

  # This job generates and deploys the report
  deploy-report:
    # This job needs the 'test' job to succeed first
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure results
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Generate and deploy Allure report to GitHub Pages
        uses: allure-framework/allure-github-action@v1.6.1
        with:
          # The path where the report will be generated
          report_dir: allure-report
          # The branch to which the report will be deployed
          gh_pages: gh-pages
          # A prefix for the report URL
          report_id: youtrack-aqa-report
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4